add_newline = true

format = '$directory($git_branch$git_status$python) $character '

command_timeout = 2000

[character]
success_symbol = "[... •](bold green)" 
error_symbol = "[... •](bold red)" 
vicmd_symbol = "[... •](bold cyan)" 

[git_branch]
format = '[\($branch\)](bright-black)'

[git_status]
format = "[$all_status]($style)"
conflicted = "="
ahead = ""
behind = ""
diverged = ""
untracked = "?"
stashed = "≠"
modified = "*"
staged = "+"
renamed = ""
deleted = "–"
disabled = false

[python]
format = '[${pyenv_prefix}(${version} )(\($virtualenv\) )](bright-black)'
